// <auto-generated />
namespace Emploee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addjobposition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addjobposition));
        
        string IMigrationMetadata.Id
        {
            get { return "201908130213102_add-jobposition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
