// <auto-generated />
namespace Emploee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_PostDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_PostDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201910090909026_Update_PostDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
